# Generated by Django 5.2.6 on 2025-09-26 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a2s_system', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacherprofile',
            name='specialization',
        ),
        migrations.RemoveField(
            model_name='user',
            name='role',
        ),
        migrations.AddField(
            model_name='user',
            name='is_student',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='is_teacher',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='program',
            field=models.CharField(default='Undeclared', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='year_level',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='teacherprofile',
            name='department',
            field=models.CharField(default='Undeclared', max_length=100),
            preserve_default=False,
        ),
    ]
