# Generated by Django 5.2.7 on 2025-10-18 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('a2s_system', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Curriculum',
        ),
    ]
