# Generated by Django 5.2.6 on 2025-09-26 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a2s_system', '0002_remove_teacherprofile_specialization_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='id_number',
            field=models.CharField(blank=True, max_length=12, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
