# Generated by Django 5.2.6 on 2025-10-07 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a2s_system', '0006_studentprofile_academic_standing_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='program',
            field=models.CharField(default='Undeclared', max_length=100),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='year_level',
            field=models.IntegerField(default=1),
        ),
    ]
