# Generated by Django 5.2.6 on 2025-10-08 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a2s_system', '0009_curriculum'),
    ]

    operations = [
        migrations.RenameField(
            model_name='grade',
            old_name='grade',
            new_name='status',
        ),
        migrations.AddField(
            model_name='grade',
            name='final',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='grade',
            name='final_grade',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='grade',
            name='midterm',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='grade',
            name='school_year',
            field=models.CharField(default=2324, max_length=9),
        ),
        migrations.AddField(
            model_name='grade',
            name='semester',
            field=models.CharField(default='1st Semester', max_length=20),
        ),
    ]
