# Generated by Django 5.2.6 on 2025-10-08 13:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a2s_system', '0010_rename_grade_grade_status_grade_final_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='grade',
            name='faculty',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='grade',
            name='units',
            field=models.IntegerField(default=3),
        ),
        migrations.AlterField(
            model_name='grade',
            name='school_year',
            field=models.CharField(default='2324', max_length=9),
        ),
        migrations.AlterField(
            model_name='grade',
            name='semester',
            field=models.CharField(default='First', max_length=20),
        ),
        migrations.AlterField(
            model_name='grade',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='a2s_system.studentprofile'),
        ),
    ]
