# Generated by Django 5.2.6 on 2025-10-11 12:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a2s_system', '0013_teacherprofile_address_teacherprofile_bio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherprofile',
            name='achievements',
            field=models.ManyToManyField(blank=True, related_name='teacher_profiles', to='a2s_system.achievement'),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='position',
            field=models.CharField(choices=[('Full-Time Faculty', 'Full-Time Faculty'), ('Part-Time Faculty', 'Part-Time Faculty'), ('Visiting Lecturer', 'Visiting Lecturer'), ('Adjunct Faculty', 'Adjunct Faculty')], default='Full-Time Faculty', max_length=50),
        ),
        migrations.AlterField(
            model_name='teacherachievement',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_achievements', to='a2s_system.teacherprofile'),
        ),
    ]
