# Generated by Django 5.2.6 on 2025-10-11 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a2s_system', '0014_teacherprofile_achievements_teacherprofile_position_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacherprofile',
            name='department',
            field=models.CharField(blank=True, choices=[('CEA', 'Engineering and Architecture'), ('CCS', 'Computer Studies'), ('CASE', 'Arts, Sciences and Education'), ('CMBA', 'Management, Business and Accountancy'), ('CNAHS', 'Nursing and Allied Health Sciences'), ('CCJ', 'Criminal Justice')], max_length=50, null=True),
        ),
    ]
