# Generated by Django 5.2.7 on 2025-10-14 09:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('dob', models.DateField(blank=True, null=True)),
                ('bio', models.TextField(blank=True, null=True)),
                ('specialization', models.CharField(blank=True, max_length=100, null=True)),
                ('position', models.CharField(choices=[('Full-Time Faculty', 'Full-Time Faculty'), ('Part-Time Faculty', 'Part-Time Faculty'), ('Visiting Lecturer', 'Visiting Lecturer'), ('Adjunct Faculty', 'Adjunct Faculty')], default='Full-Time Faculty', max_length=50)),
                ('department', models.CharField(blank=True, choices=[('CEA', 'Engineering and Architecture'), ('CCS', 'Computer Studies'), ('CASE', 'Arts, Sciences and Education'), ('CMBA', 'Management, Business and Accountancy'), ('CNAHS', 'Nursing and Allied Health Sciences'), ('CCJ', 'Criminal Justice')], max_length=50, null=True)),
                ('achievements', models.ManyToManyField(blank=True, related_name='teacher_profiles', to='students.achievement')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TeacherAchievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('icon', models.CharField(default='award', max_length=50)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_achievements', to='faculty.teacherprofile')),
            ],
        ),
    ]
