# Generated by Django 5.2.7 on 2025-10-14 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Curriculum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('program', models.CharField(max_length=50)),
                ('data', models.JSONField()),
            ],
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='program',
            field=models.CharField(choices=[('CEA', 'Engineering and Architecture'), ('CCS', 'Computer Studies'), ('CASE', 'Arts, Sciences and Education'), ('CMBA', 'Management, Business and Accountancy'), ('CNAHS', 'Nursing and Allied Health Sciences'), ('CCJ', 'Criminal Justice')], default='CCS', max_length=50),
        ),
    ]
