# Generated by Django 5.2.7 on 2025-10-14 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_curriculum_alter_studentprofile_program'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='program',
            field=models.CharField(default='Undeclared', max_length=100),
        ),
    ]
