# Generated by Django 5.2.7 on 2025-10-26 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_courseassignment'),
        ('teacher', '0002_remove_schedule_subject_name'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='courseassignment',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='courseassignment',
            name='section',
            field=models.CharField(default='G1', max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='courseassignment',
            unique_together={('student', 'teacher', 'course_code', 'section')},
        ),
    ]
