# Generated by Django 5.2.7 on 2025-10-28 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_alter_courseassignment_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='grade',
            name='notes',
            field=models.TextField(blank=True),
        ),
    ]
