# Generated by Django 5.2.7 on 2025-10-18 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_alter_studentprofile_program'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='curriculum',
            table='a2s_system_curriculum',
        ),
    ]
