# Generated by Django 5.2.7 on 2025-10-28 08:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_grade_notes'),
        ('teacher', '0002_remove_schedule_subject_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='grade',
            name='teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='teacher.teacherprofile'),
        ),
    ]
