# Generated by Django 5.2.7 on 2025-10-30 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0008_alter_studentprofile_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='profile_picture',
            field=models.URLField(blank=True, null=True),
        ),
    ]
