# Generated by Django 5.2.7 on 2025-10-25 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='subject_name',
        ),
    ]
