# Generated by Django 5.2.7 on 2025-10-31 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0002_remove_schedule_subject_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherprofile',
            name='profile_picture',
            field=models.URLField(blank=True, null=True),
        ),
    ]
